### ISSUE TITLE
Panic when patching a node with data from proccon

### ISSUE THREAD

**Issue by adrianlzt** [datadope-io/skydive#6]
# Steps to reproduce
1. Create a node using proccon:
```
curl localhost:4000 -XPOST -d '{
  "metrics": [
    {
      "fields": {
        "listen": "",
        "conn": "33.33.33.33:3333,192.168.1.36:8000,1.1.1.1:80"
      },
      "name": "procstat_test",
      "tags": {
        "cmdline": "misoft.exe",
        "host": "archer",
        "process_name": "softmMi"
      },
      "timestamp": 1603890666
    }
  ]
}'
```

2. Patch the node to add new metadata
```
curl  -H "Content-Type: application/json" -XPATCH localhost:8082/api/node/ad35dcba-a689-481f-5046-6b0d86ad9c9e  -d '[{"op": "add", "path": "/Metadata/Icon", "value": ""}]'
```

Skydive panics:
```
2021-03-01 19:58:10.226818 I | http: panic serving 127.0.0.1:51282: interface conversion: interface {} is map[string]interface {}, not *proccon.NetworkInfo
goroutine 153653 [running]:
net/http.(*conn).serve.func1(0xc0018a8000)
        /usr/lib/go/src/net/http/server.go:1824 +0x153
panic(0x4bbea00, 0xc0021bd320)
        /usr/lib/go/src/runtime/panic.go:971 +0x499
github.com/skydive-project/skydive/topology/probes/procpeering.listenEndpointHasher(0xc00222bb90, 0xc0007cc510)
        /home/adrian/go/src/github.com/skydive-project/skydive/topology/probes/procpeering/procpeering.go:183 +0x387
github.com/skydive-project/skydive/graffiti/graph.(*Indexer).OnNodeUpdated(0xc000417620, 0xc00222bb90, 0x0, 0x0, 0x0)
        /home/adrian/go/src/github.com/skydive-project/skydive/graffiti/graph/indexer.go:140 +0x38
github.com/skydive-project/skydive/graffiti/graph.(*EventHandler).notifyListeners(0xc000238aa0, 0x1, 0x501d520, 0xc00222bb90, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/adrian/go/src/github.com/skydive-project/skydive/graffiti/graph/graph.go:263 +0x208
github.com/skydive-project/skydive/graffiti/graph.(*EventHandler).NotifyEvent(0xc000238aa0, 0x1, 0x501d520, 0xc00222bb90, 0x0, 0x0, 0x0)
        /home/adrian/go/src/github.com/skydive-project/skydive/graffiti/graph/graph.go:294 +0x1c5
github.com/skydive-project/skydive/graffiti/graph.(*Graph).SetMetadata(0xc0001c3d40, 0x501d520, 0xc00222bb90, 0xc001535320, 0xc00170c800, 0x1)
        /home/adrian/go/src/github.com/skydive-project/skydive/graffiti/graph/graph.go:786 +0x186
github.com/skydive-project/skydive/graffiti/api/server.(*NodeAPIHandler).Update(0xc000716b98, 0xc002788050, 0x24, 0x57a7e98, 0xc0015a6480, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/adrian/go/src/github.com/skydive-project/skydive/graffiti/api/server/node.go:145 +0x277
github.com/skydive-project/skydive/graffiti/api/server.patchMethod(0x57d9428, 0xc000716b98, 0x570aa80, 0xc00000f2d8, 0xc002788050, 0x24, 0xc0023ba000, 0x39, 0x200, 0x203000, ...)
        /home/adrian/go/src/github.com/skydive-project/skydive/graffiti/api/server/server.go:495 +0x7a5
github.com/skydive-project/skydive/graffiti/api/server.(*Server).RegisterAPIHandler.func5(0x579b090, 0xc0027060e0, 0xc001d3a7e0)
        /home/adrian/go/src/github.com/skydive-project/skydive/graffiti/api/server/server.go:249 +0x216
github.com/skydive-project/skydive/graffiti/http.(*NoAuthenticationBackend).Wrap.func1(0x579b090, 0xc0027060e0, 0xc0024a2300)
        /home/adrian/go/src/github.com/skydive-project/skydive/graffiti/http/noauth.go:56 +0xd0
net/http.HandlerFunc.ServeHTTP(0xc0004e0270, 0x579b090, 0xc0027060e0, 0xc0024a2300)
        /usr/lib/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001d2e40, 0x579b090, 0xc0027060e0, 0xc0024a2100)
        /home/adrian/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/gorilla/handlers.(*cors).ServeHTTP(0xc000feebd0, 0x579b090, 0xc0027060e0, 0xc0024a2100)
        /home/adrian/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/cors.go:54 +0x103e
github.com/gorilla/handlers.CompressHandlerLevel.func1(0x579b090, 0xc0027060e0, 0xc0024a2100)
        /home/adrian/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/compress.go:100 +0x8eb
net/http.HandlerFunc.ServeHTTP(0xc000622d80, 0x579b090, 0xc0027060e0, 0xc0024a2100)
        /usr/lib/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc000103e18, 0x579b090, 0xc0027060e0, 0xc0024a2100)
        /usr/lib/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0018a8000, 0x57a6298, 0xc0006262c0)
        /usr/lib/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
        /usr/lib/go/src/net/http/server.go:3013 +0x39b
```

**Comment by adrianlzt** [comment]
fixed in 4792e3e9
